### ISSUE TITLE
Documentation for initial setup

### ISSUE THREAD

**Issue by codehearts** [TuyaAPI/link#1]
I've been following the discussions on the tuyapi repo, but I still find myself a little confused about how to set this thing up. It would be good to have concise documentation on how to set up a cloud account (and around how long to wait for that), how manually generating your device key isn't possible (or is it?), and how to find the ssid of your device.

I'm going through this process right now, so I wouldn't mind drafting something and opening a PR once I've set up things on my end.

**Comment by codetheweb** [comment]
Sorry about the confusion.

I've been working on a CLI NodeJS package over the last couple of days that will effectively act as a more user-friendly wrapper around this package (`@tuyapi/link`) and the base tuyapi package (`codetheweb/tuyapi`).

Once that's finished, I'm planning to add documentation for using it to set up devices in tuyapi's readme.

For now, if you copy the usage example for this package into a new file and replace `apiKey`, `apiSecret`, `ssid`, and `wifiPassword` with the appropriate values it should work (parameters for WiFi should be taken from your network; devices don't broadcast a network).

**Comment by codehearts** [comment]
I've been looking into this again, but I can't figure out where to obtain an API key and secret. Do I need to sign up at developer.tuya.com and then complete the enterprise information form (with fake data, I assume?), or is that the wrong avenue?

**Comment by codetheweb** [comment]
Yep, apply for an account @codehearts.  Doesn't necessarily need to be fake information; they don't seem to care if individuals register.  It took me around 3 days to be approved for API access.

Although just as a warning some of the endpoints are not working for me right now, meaning they likely updated them without updating the documentation

**Comment by codetheweb** [comment]
Hey @codehearts, everything is now working.  Follow [these](https://github.com/codetheweb/tuyapi/blob/v3.0.1/docs/SETUP.md) instructions to obtain API keys and link a device.
