### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by milo526** [TuyaAPI/link#11]
Currently this library is written in JavaScript and does not expose any TypeScript types.

I see that some of your (@codetheweb) personal projects are written in TypeScript.
Would you be open to a Pull Requests that "rewrites" this library in TypeScript and that exports the types of this library?

Just wanted to confirm this with you before I start investing time 🙂

**Comment by codetheweb** [comment]
👍 that sounds great to me!

**Comment by milo526** [comment]
Awesome! Then I'll start working on this shortly.
Could you maybe assign me to this issue so it is clear for others that it is being worked on?
