### ISSUE TITLE
Extract client and server code

### ISSUE THREAD

**Issue by milo526** [TuyaAPI/link#12]
I believe this library could benefit from some code separation, mostly separating client and server code.

In my view the Client should not know the client ID and secret and the server does not need to know the SSID and wifi password.

In the current projects for which you use this library this is not of serious concern since there is one place that acts as both the server and the client.

I am however working on a system that would require the client credentials to be kept secret and it would be nice to have separation between these two concerns.

Would you be open to a Pull request that introduces these changes?

**Comment by codetheweb** [comment]
Sorry, I'm a little confused on how you're defining server and client code.

What parts of this library fall under what category?

**Comment by milo526** [comment]
Yeah me neither, looking at this some more I guess my answer would mostly be:

Use the cloud package on the server.  
Use the Link.manual locally.

I was thinking only in the way of the Link.wizard and how that uses client side secrets (wifi password) as well as server side secrets (tuya app client-secret)

**Comment by codetheweb** [comment]
Ok.

Feel free to rename the exports if you want too when doing #11; 

```typescript
import {manual} from '@tuyapi/link'
```

isn't super readable when just calling `manual` 100 lines down. 😛

**Comment by milo526** [comment]
On the one hand that seems great, on the other hand that would introduce a breaking change.
I don't think adding typings in itself would be or would require a breaking change.

Furthermore you could of course use 
```javascript
import {manual as ManualDeviceLinker} from '@tuyaapi/link'

// 100 lines later

ManualDeviceLinker()
```
to prevent this

**Comment by codetheweb** [comment]
I'm ok with a breaking change, but good point with import aliases.
