### ISSUE TITLE
TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by jemantilla** [TuyaAPI/link#13]
I'm trying to use this in the client side. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/54767649/113139405-a3a24f00-9259-11eb-8b7e-9f3317c19253.png)

![image](https://user-images.githubusercontent.com/54767649/113139509-cb91b280-9259-11eb-8e02-452e77a755bc.png)

My node version: 15.10

**Comment by codetheweb** [comment]
> I'm trying to use this in the client side. Am I doing something wrong?

Yes. This only works in Node because it needs direct access to sockets.

**Comment by jemantilla** [comment]
> > I'm trying to use this in the client side. Am I doing something wrong?
> 
> Yes. This only works in Node because it needs direct access to sockets.

But how am I going to link a device if its going to just get the localhost of the server's IP when i link using ssid? 
![image](https://user-images.githubusercontent.com/54767649/113219967-feb55f80-92b4-11eb-9fa5-d6204f87bcc3.png)

**Comment by codetheweb** [comment]
> But how am I going to link a device if its going to just get the localhost of the server's IP when i link using ssid?

Sorry, not understanding what you're saying. What's going to use localhost?

**Comment by jemantilla** [comment]
> > But how am I going to link a device if its going to just get the localhost of the server's IP when i link using ssid?
> 
> Sorry, not understanding what you're saying. What's going to use localhost?

Since i'll deploy this to the cloud, how will it detect my wifi to get the devices to link? sorry am i asking the right question? haha since its for node i'll deploy it to the cloud. But problem is it cant detect my wifi using:
![image](https://user-images.githubusercontent.com/54767649/113225717-de8b9d80-92c0-11eb-8ef7-8d03f1708a58.png)

since its in the server.

**Comment by jemantilla** [comment]
> > > But how am I going to link a device if its going to just get the localhost of the server's IP when i link using ssid?
> > 
> > 
> > Sorry, not understanding what you're saying. What's going to use localhost?
> 
> Since i'll deploy this to the cloud, how will it detect my wifi to get the devices to link? sorry am i asking the right question? haha since its for node i'll deploy it to the cloud. But problem is it cant detect my wifi using:
> ![image](https://user-images.githubusercontent.com/54767649/113225717-de8b9d80-92c0-11eb-8ef7-8d03f1708a58.png)
> 
> since its in the server.

Follow up on this? sorry i need help :(

**Comment by codetheweb** [comment]
Your Tuya device and the computer you're running this on must be on the same network. Running this on a remote server will not work.

**Comment by jemantilla** [comment]
> Your Tuya device and the computer you're running this on must be on the same network. Running this on a remote server will not work.

Got this. Thank you!

**Comment by jemantilla** [comment]
Follow up question @codetheweb, since this must be on a same network how can we use this for an app then if will not work on a remote server? Im using Ionic React. I cant use node js in frontend at all and i cant deploy this to the remote server. How can we use pairing service of tuyalink api?

**Comment by codetheweb** [comment]
I'm not sure what your application is but one solution might be to bundle your frontend as an Electron app. You would then have access to a full Node.js runtime locally.

**Comment by jemantilla** [comment]
> I'm not sure what your application is but one solution might be to bundle your frontend as an Electron app. You would then have access to a full Node.js runtime locally.

Ok I'll check this out. Im using Ionic React BTW thank you!
