### ISSUE TITLE
Sign Invalid

### ISSUE THREAD

**Issue by beks-sudo** [TuyaAPI/link#14]
Following the documentation I bumped into an error

{ code: 1004, msg: 'sign invalid', success: false, t: 1626081150299 }

`const TuyaLink = require('./index.js');

const register = new TuyaLink.wizard({
    apiKey: 't984uehwxxxxxxxxxxxx',
    apiSecret: 'd87da6xxxxxxxxxxxxxxxc3899621d',
    email: 'my-sweet-mail@gmail.com',
    password: 'fantastic-password',
    region: 'eu',
    // timezone: '00:00'
});

register.init().catch(function (e) {
    console.log(e)
})`

I need help

**Comment by codetheweb** [comment]
https://github.com/TuyaAPI/cli/issues/130

**Comment by ThodorisElissaios** [comment]
same here

**Comment by codetheweb** [comment]
Fixed in v0.3.4.

**Comment by Barnyvic** [comment]
how did you fix this error pls?
