### ISSUE TITLE
Next Step in Installation

### ISSUE THREAD

**Issue by celeritas0725** [TuyaAPI/link#5]
Im stucked in installing npm i @tuyapi/link.
What's next? how can I use this code?
Any help is appreciated.
Thanks!

**Comment by codetheweb** [comment]
Given your issue [here](https://github.com/codetheweb/tuyapi/issues/308#issuecomment-611544962), I'm guessing you just want to link your devices using `tuya-cli`.

This package is not intended for use by end-users.
