### ISSUE TITLE
Having hard time to understand Token, Region, Secret

### ISSUE THREAD

**Issue by omersiar** [TuyaAPI/link#7]
Hello,

Tuya Javascript collection is just amazing, thank you.

I just want to understand what does Token, Region and Secret changes for SmartConfig and why they are calculated for length of the UDP packages.

https://github.com/espressif/ESP8266_RTOS_SDK/tree/52f9d8c1b88cafc371a2d10a519e0d108afe2f1a/examples/wifi/smart_config

No usable example out there.

Mobile SmartConfig apps seems does not care about Token, Region and Secret and just calculates array from the BSSID, SSID, Passphrase.

https://www.espressif.com/sites/default/files/documentation/esp-touch_user_guide_en.pdf

I'm not using Tuya firmware, I'm trying to create one using Arduino framework.

smartconfig_get_version() outputs
Smartconfig Version: V2.5.4

**Comment by omersiar** [comment]
My test code

```c++
const TuyaLink = require('@tuyapi/link');

const register = new TuyaLink.manual();

register.registerSmartLink({region: 'EU',
                           token: '00000000',
                           secret: '0000',
                           ssid: 'Hack_This!',
                           wifiPassword: 'asdasd'}).then(() => {
  console.log('Done!');
 });
```

**Comment by omersiar** [comment]
I have captured UDP packages with Wireshark, not exactly as if have been with mobile application.

**Comment by codetheweb** [comment]
I don't think that code/library you linked to and Tuya's solution are the same thing.  Tuya calls their protocol 'Smart Link', and yours is called 'Smart Config'.

Are you looking for help with the ESP library, or linking a Tuya device?

**Comment by omersiar** [comment]
Smart Link is like Smart Config but with an additional cloud pairing step. Manual mode implies that is only connecting to the Local Network. I'm trying to code a CLI tool for my firmware.  No need to left open this issue. Thank you.
