### ISSUE TITLE
Custom cloud

### ISSUE THREAD

**Issue by jpillora** [TuyaAPI/link#9]
Is it possible to skip the Tuya cloud all together and perform a local register? I've got a Tuya battery motion sensor and I'd like it to interact with a local webserver instead of Tuya cloud. I also run my own DNS server so I can intercept requests to a given domain (assuming IPs aren't hardcoded and certificates  aren't pinned...). https://github.com/TuyaAPI/register seems to redirect here

Have you attempted this before?

**Comment by codetheweb** [comment]
I personally have not attempted it. But it is very possible; for example the [tuya-convert](https://github.com/ct-Open-Source/tuya-convert) project simulates a local server during registration.

You may find [this repo](https://github.com/kueblc/mocktuyacloud) useful.

**Comment by jpillora** [comment]
Thanks for the links :)
